server:
  port: 8100

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/db_codingrecipe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/godcoder?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
    # spring data jpa 설정
  jpa:
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
  # ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
    com:
      godcoder: DEBUG

mybatis:
  type-aliases-package: com.godcoder.myrest.model
#  type-handlers-package: com.example.typehandler
  configuration:
    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
  mapper-locations:
  - classpath:mapper/**/*.xml